language: python
python:
    - "3.5"
    - "3.4"
install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
before_script:
    - psql -c 'create database test;' -U postgres
script:
    - flake8
    - python -m unittest tests/*.py
services:
    - postgresql
addons:
  postgresql: "9.2"
