language: python
dist: xenial
python:
    - "3.8"
    - "3.7"
    - "3.6.3"
sudo: required
before_install:
    - pip install --upgrade pip
install:
    - make build
    - pip install codecov
    - pip install -r test_requirements.txt
before_script:
    - psql -c 'create database test;' -U postgres
    - psql -c "grant all privileges on database test to postgres;" -U postgres
script:
    - flake8 --exclude lib
    - pytest -v tests/ --cov=server --cov-report html
services:
    - postgresql
after_success:
    - codecov
addons:
  postgresql: "9.6"
