openapi: 3.0.2

info:
  title: sdx-store
  description: A service for storing and retrieving SDX data
  version: "3.13.2"

servers:
  - url: http://localhost:8085/

paths:
  /healthcheck:
    get:
      summary: Healthcheck.
      description: Simple endpoint that reports the health of the application.
      responses:
        200:
          description: Healthcheck retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
        400:
          $ref: '#/components/responses/InvalidUsageError'
        500:
          $ref: '#/components/responses/ServerError'
  /info:
    $ref: '#/paths/~1healthcheck'

  /responses:
    post:
      summary: Store response
      description: Store a json survey response
      requestBody:
        $ref: '#/components/requestBodies/Survey'
      responses:
        200:
          $ref: '#/components/responses/Success'
        400:
          $ref: '#/components/responses/InvalidUsageError'
        500:
          $ref: '#/components/responses/ServerError'
    get:
      summary: Retrieve valid responses
      description: retrieve all valid responses as json
      responses:
        200:
          $ref: '#/components/responses/SurveyList'
        500:
          $ref: '#/components/responses/ServerError'

  /responses/{tx_id}:
    get:
      summary: Retrieve response with tx_id
      description: Retrieve response with tx_id as json
      parameters:
        - $ref: '#/components/parameters/tx_id'
      responses:
        200:
          $ref: '#/components/requestBodies/Survey'
        400:
          $ref: '#/components/responses/InvalidUsageError'
        500:
          $ref: '#/components/responses/ServerError'

  /responses/old:
    delete:
      summary: Delete old responses
      description: Deletes responses that are older than the number of days set in config
      responses:
        204:
          description: Ran succesfully
        500:
          $ref: '#/components/responses/ServerError'

  /invalid-responses:
    get:
      summary: Retrieve invalid responses
      description: retrieve all invalid responses as json
      responses:
        200:
          $ref: '#/components/responses/SurveyList'
        500:
          $ref: '#/components/responses/ServerError'

components:
  parameters:
    tx_id:
      name: tx_id
      description: Transaction id
      in: path
      required: true
      schema:
        type: string
        example: "b7f78b30-1814-45ac-963d-8c997c091f90"
  responses:
    Success:
      description: Succesfully completed
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                type: string
                example: "ok"
    SurveyList:
      description: List of survey responses in json
      content:
        application/json:
          schema:
            type: array
            items:
              items:
                $ref: '#/components/schemas/SurveyResponse/properties'

    InvalidUsageError:
      description: Invalid usage error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Missing transaction id. Unable to save response"

    ServerError:
      description: Server error.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              message:
                type: string
                example: "Internal server error ..."

  requestBodies:
    Survey:
      description: survey
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SurveyResponse'

  schemas:
    SurveyResponse:
      type: object
      properties:
        type:
          type: string
          example: "uk.gov.ons.edc.eq:surveyresponse"
        origin:
          type: string
          example: "uk.gov.ons.edc.eq"
        survey_id:
          type: string
          example: "023"
        version:
          type: string
          example: "0.0.1"
        tx_id:
          type: string
          example: "b7f78b30-1814-45ac-963d-8c997c091f90"
        collection:
          type: object
          properties:
            exercise_sid:
              type: string
              example: "hfjdskf"
            instrument_id:
              type: string
              example: "0203"
            period:
              type: string
              example: "0216"
        submitted_at:
          type: string
          example: "2016-03-12T10:39:40Z"
        metadata:
          type: object
          properties:
            user_id:
              type: string
              example: "789473423"
            ru_ref:
              type: string
              example: "12345678901A"
        data:
          type: object
          example: '"11": "01/04/2016",
                    "12": "31/10/2016",
                    "20": "1800000",
                    "51": "84",
                    "146": "some comment"'