CREATE TABLE IF NOT EXISTS responses (id uuid PRIMARY KEY, ts timestamp WITH time zone DEFAULT NOW(), valid boolean DEFAULT NULL, data jsonb);
CREATE SEQUENCE sequence MINVALUE 1000 MAXVALUE 9999 CYCLE;
CREATE SEQUENCE batch_sequence MINVALUE 30000 MAXVALUE 39999 CYCLE;
CREATE SEQUENCE image_sequence MINVALUE 1 MAXVALUE 999999999 CYCLE;
CREATE SEQUENCE json_sequence MINVALUE 1 MAXVALUE 999999999 CYCLE;